# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-30 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_add_primary_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='full_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
