# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-30 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180530_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='real_degree',
            field=models.IntegerField(default=97),
        ),
    ]
