# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-30 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_real_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fake_or_real_tf_idf',
            field=models.CharField(default=b'REAL', max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='fake_or_real_word_count',
            field=models.CharField(default=b'REAL', max_length=10),
        ),
    ]
